# Parameters for apriltag_ros's apriltag_ros_continuous_node
apriltag_detector:
  # a list of all the tags the AprilTag detector should be looking for. 
  # The first entry is used for calibration.
  standalone_tags: [            
    {id: 4, size: 0.014, name: "detected_calibration_tag"}
  ]
  tag_family:        'tag36h11' # options: tagStandard52h13, tagStandard41h12, tag36h11, tag25h9, tag16h5, tagCustom48h12, tagCircle21h7, tagCircle49h12
  tag_threads:       2          # default: 2
  tag_decimate:      1.0        # default: 1.0
  tag_blur:          0.0        # default: 0.0
  tag_refine_edges:  1          # default: 1
  tag_debug:         0          # default: 0
  max_hamming_dist:  2          # default: 2 (Tunable parameter with 2 being a good choice - values >=3 consume large amounts of memory. Choose the largest value possible.)
  publish_tf:        true
  publish_tag_detections_image: true
  transport_hint:    "compressed"      # default: raw, see http://wiki.ros.org/image_transport#Known_Transport_Packages for options
fixed_tag_frame: "calibration_tag"
camera_frame: "camera_link"
# This transform is used initially if AprilTag does not detect the calibration tag. 
# Another way to think about this is the camera's pose in the tag's frame.
tag_to_camera_default_transform:
  translation: [0.019, 0.099, 0.066]
  rotation: [0.123,0.104, -0.679, 0.716]