# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

group_joint_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  gains:
      joint_1: {p: 3000.0, i: 0.0, d: 2.0, i_clamp_min: -100.0, i_clamp_max: 100.0}
      joint_2: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -5.0, i_clamp_max: 5.0}
      joint_3: {p: 50000.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
      joint_4: {p: 750.0, i: 0.0, d: 0.2, i_clamp_min: -1.0, i_clamp_max: 1.0}
      joint_5: {p: 5000.0, i: 0.0, d: 1.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
      joint_6: {p: 100.0, i: 0.0, d: 0.0, i_clamp_min: -0.1, i_clamp_max: 0.1}

# whole-arm base velocity controller
velocity_controller:
  mode: VELOCITY
  mode_handle: joint_mode
  type: pr_ros_controllers/JointGroupVelocityController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]

# whole-arm base position controller
position_controller:
  mode: POSITION
  mode_handle: joint_mode
  type: pr_ros_controllers/JointGroupPositionController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]

# whole-arm base effort controller
effort_controller:
  mode: EFFORT
  mode_handle: joint_mode
  type: pr_ros_controllers/JointGroupEffortController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]

# whole-arm base trajectory controller
trajectory_controller:
  mode: TRAJECTORY
  type: velocity_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]
  constraints:
    stopped_velocity_tolerance: 1.0
    joint_1:
      goal: 0.02
      trajectory: 0.05
    joint_2:
      goal: 0.02
      trajectory: 0.05
    joint_3:
      goal: 0.02
      trajectory: 0.05
    joint_4:
      goal: 0.02
      trajectory: 0.05
    joint_5:
      goal: 0.02
      trajectory: 0.05
    joint_6:
      goal: 0.02
      trajectory: 0.05
  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}

# whole-arm base trajectory controller
move_until_touch_topic_controller:
  mode: TRAJECTORY
  type: rewd_controllers/MoveUntilTouchTopicController
  # Forque Sensor
  forcetorque_wrench_name: /forque/forqueSensor
  forcetorque_tare_name: /forque/bias_controller/trigger
  # FingerVision
  # forcetorque_wrench_name: /fingervision/fv_3_l/wrench
  # forcetorque_tare_name: /fingervision/fingerVisionTaring
  sensor_force_limit: 50
  sensor_torque_limit: 5
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]
  control_type: velocity
  constraints:
    joint_1:
      goal: 0.02
      trajectory: 0.05
    joint_2:
      goal: 0.02
      trajectory: 0.05
    joint_3:
      goal: 0.02
      trajectory: 0.05
    joint_4:
      goal: 0.02
      trajectory: 0.05
    joint_5:
      goal: 0.02
      trajectory: 0.05
    joint_6:
      goal: 0.02
      trajectory: 0.05
  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}

# Optional controller that might be useful for testing.
# Should do the same thing as trajectory_controller, but this is 
# the lab's rewd_controllers implementation
rewd_trajectory_controller:
  mode: TRAJECTORY
  type: rewd_controllers/JointTrajectoryController
  joints: [joint_1, joint_2, joint_3,
    joint_4, joint_5, joint_6]
  constraints:
    stopped_velocity_tolerance: 1.0
    joint_1:
      goal: 0.02
      trajectory: 0.05
    joint_2:
      goal: 0.02
      trajectory: 0.05
    joint_3:
      goal: 0.02
      trajectory: 0.05
    joint_4:
      goal: 0.02
      trajectory: 0.05
    joint_5:
      goal: 0.02
      trajectory: 0.05
    joint_6:
      goal: 0.02
      trajectory: 0.05
  gains: # Required because we're controlling a velocity interface
    joint_1: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_2: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_3: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_4: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_5: {p: 3,  d: 0, i: 0, i_clamp: 1}
    joint_6: {p: 3,  d: 0, i: 0, i_clamp: 1}
  control_type: velocity