# Gen3 ADA configuration parameters
default_urdf: package://kortex_description/robots/gen3_6dof_vision.urdf
default_srdf: package://kortex_description/robots/gen3_6dof.srdf
default_accel_lim: 2.0
default_vel_lim: 0.7
end_effector: robotiq_arg2f_base_link
arm: [base_link, bracelet_link]
hand_base: end_effector_link
arm_controller: trajectory_controller
hand_controller: hand_controller
named_configs: package://libada/resources/g2_6d_named_configs.yaml  
arm_executors:
  enable_controller_switching: true
  mode_controller: joint_mode_controller
  # Note: type can be TRAJECTOTY / JOINT_COMMAND / TASK_COMMAND / VISUAL_SERVOING
  # Note: executor mode can be different from controller mode, for example joint command position executor and impedance controller
  # Note: type TRAJECTORY does not require mode specification
  # Note: last-controller is default when calling setActiveExecutor(ExecutorType)
  executors:
    - {id: effort_trajectory_executor, type: TRAJECTORY, mode: EFFORT, controller: effort_joint_trajectory_controller}
    - {id: velocity_trajectory_executor, type: TRAJECTORY, mode: VELOCITY, controller: move_until_touch_topic_joint_trajectory_controller}
    - {id: bite_transfer_executor, type: JOINT_COMMAND, mode: EFFORT, controller: task_space_compliant_controller}
  # executors:
  #   - {id: velocity_trajectory_executor, type: TRAJECTORY, mode: VELOCITY, controller: rewd_trajectory_controller}
  #   - {id: bite_transfer_executor, type: JOINT_COMMAND, mode: EFFORT, controller: task_space_compliant_controller}
hand_executors:
  enable_controller_switching: true
  mode_controller: hand_mode_controller
  # Note: type can be TRAJECTOTY / JOINT_COMMAND / TASK_COMMAND / VISUAL_SERVOING
  # Note: executor mode can be different from controller mode, for example joint command position executor and impedance controller
  # Note: last-controller is default when calling setActiveExecutor(ExecutorType)
  executors:
    - {id: forque_pickup_executor, type: JOINT_COMMAND, mode: POSITION, controller: hand_position_controller}